-- setup関数を記述するとneovim起動時にNeoTreeが自動的に起動しちゃうのでコメントにした
-- require('neo-tree').setup({
-- 	filesystem = {
-- 		window = {
-- 			width = 30, -- ここで幅を設定します。数値は任意で変更可能です。
-- 		},
-- 		filtered_items = {
-- 			visible = false, -- when true, they will just be displayed differently than normal items
-- 			hide_dotfiles = true,
-- 			hide_gitignored = true,
-- 			hide_hidden = true, -- only works on Windows for hidden files/directories
-- 			hide_by_name = {
-- 				--"node_modules"
-- 			},
-- 		},
-- 	},
-- })
